### ISSUE TITLE
Feature suggestions: Rearrange menu option and Share button

### ISSUE THREAD

**Issue by TrentMage** [foamify/shakepin#2]
Hey! First of all, I’m loving the app. I use it pretty much every day as I’m a college student that does a lot of dragging and dropping pdf’s into online editors or sharing images and the like. If you wouldn’t mind taking feature suggestions I have two.

1. Are you able to add the ability to rearrange the menu that pops up after shaking the file? It’s very minor but I use the pin option the most and it’d be nice to immediately shake then drop the file to have it pinned.
2. Can you add a share option? It could just be a button in the pinned items section like with the close and minimize, maybe in the top right, something like in the image attached? I appreciate it :)
![IMG_3320](https://github.com/user-attachments/assets/1e978338-6ddf-4c51-b70e-111b08e413b6)

**Comment by damywise** [comment]
Hi @TrentMage Sorry for the late reply. Glad it’s been helpful for your college life

1. I'll keep this in mind for future update. But for now I will not change this, sorry.
2. This is an interesting idea. Here's what it will look like in the next version.

<img width="312" alt="Screenshot 2024-10-20 at 16 15 26" src="https://github.com/user-attachments/assets/2cf445b3-cdb7-421a-9ed4-367868dfd4dc">

Thanks again for the feedback
